### PR TITLE
Get flusight bin endpoints

### PR DESCRIPTION
**Pull request by elray1**
This contains a general setup that I think should work for both seasons, but I ran out of time for testing the stuff for the 22/23 season, so I mostly took it out and dropped code into #16.  There are a couple of vestigial leftover bits that I didn't want to delete since we will want to recreate it at some point...

### CODE REVIEW

**Review by lshandross — APPROVED** [review]
I'm approving because everything looks good to me, but I have one minor question: why did you decide to make the sign for the bin endpoints separate columns?

**Comment by elray1** [comment]
Thanks!

> why did you decide to make the sign for the bin endpoints separate columns?

I basically felt that this was clearer when working with the `pmax` operation [here](https://github.com/reichlab/idforecastutils/blob/7b6a9c9f5f3904fd3ac0d9008c1f7f407d8bd7ad/R/get_flusight_bin_endpoints.R#L47).  If the sign is negative, what you would want is to add `pmin(.data[["lower_rate_multiplier"]] * .data[["pop100k"]], .data[["lower_min_count_change"]])`.  But you'd also need to make sure that the sign was the same for both of those arguments.  And... would it be the same pmin/pmax decision for both the lower and upper endpoints?  The answer is yes, but I coded it up wrong in my first try.

**Comment by lshandross** [comment]
One other thing to keep in mind — FluSight had slightly different category definitions for the first few weeks of the 2023/2024 season, which were then adjusted at the beginning of November 2023. I don't know if it makes sense to have an option to use these in the function to get been endpoints for the 2023/2024 season, but it's also possible this could account for some of the mismatches between quantile forecasts and the categorical ones.

**Comment by elray1** [comment]
I didn't remember that.  do you know of a place where those different category definitions are recorded?

**Comment by lshandross** [comment]
Here's a link to the specific section in the [model-output README](https://github.com/cdcepi/FluSight-forecast-hub/blob/854f091834f2a929ece2dae9124d0f255db57c3d/model-output/README.md#rate-trend-forecast-specifications) before the categories were updated in the FluSight-forecast-hub repo

**Comment by elray1** [comment]
Thanks, just noting that I filed issue #17 to address this point!

**Pull request merged**
